version: "3.8"
services: 
  database2: 
    container_name: database2
    image: mysql:latest
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=doctor
    ports: 
      - 3303:3306
      
  hospital-boot-app: 
    depends_on: 
      - database2
    restart: always
    build: .
    ports: 
      - 8040:9010
    environment:
      - spring.datasource.url=jdbc:mysql://database2:3306/doctor?useSSL=false